# Generated by Django 6.0.5 on 2026-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='content',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(default='', upload_to='knowledge/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
