# Generated by Django 6.0.5 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sustainabilityarticle_remove_knowledgebase_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
